name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a test CI script
      run: echo This first test worked!
    - name: This is a second test
      run: echo The second test worked!